### ISSUE TITLE
Hard to Debug Errors coming from `mini-css-extract-plugin` (Didn't get a result from child compiler)

### ISSUE THREAD

**Issue by phil-lgr** [seek-oss/vanilla-extract#226]
### Describe the bug

Getting an error with vanilla-extract while creating a global theme from a nested structure

```ts
// File: src/design-system/default-theme.css.ts
import { Colors, DesignSystem, Sizing } from '@newrade/core-design-system';
import { createThemeContract } from '@vanilla-extract/css';
import { defaultCSSButtons } from './default-buttons';
import { defaultCSSColors } from './default-colors';
import { defaultCSSSizing } from './default-sizing';

export const colorVars = createThemeContract<Colors<string>>(defaultCSSColors);
export const sizingVars = createThemeContract<Sizing<string>>(defaultCSSSizing);
export const buttonsVars =
  createThemeContract<Pick<DesignSystem<string>['components'], 'buttons'>>(defaultCSSButtons);
```

and then I import those in my app

```ts
// File: src/design-system/theme.css.ts
import { DesignSystem } from '@newrade/core-design-system';
import {
  buttonsVars,
  colorVars,
  defaultCSSButtons,
  defaultCSSColors,
  defaultCSSSizing,
  placeholderButtonSize,
  placeholderButtonVariant,
  sizingVars,
} from '@newrade/core-react-ui';
import { createGlobalTheme, createTheme, globalStyle } from '@vanilla-extract/css';

globalStyle('html, body', {
  margin: 0,
  padding: 0,
});

// @ts-expect-error
createGlobalTheme(':root', sizingVars, defaultCSSSizing);
// @ts-expect-error
createGlobalTheme(':root', colorVars, defaultCSSColors);
// @ts-expect-error
createGlobalTheme(':root', buttonsVars, defaultCSSButtons);
```

The expect error here is caused by #223 

When I run gatsby I get the following error:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Module build failed (from ../../node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at /Users/phil/Code/newrade-core/node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js:311:23
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:548:11
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1118:17
    at Hook.eval [as callAsync] (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
 <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1114:33
    at finalCallback (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2249:11)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2540:11
    at Hook.eval [as callAsync] (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
 <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2533:38
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)
    at _next0 (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)

File: src/design-system/theme.css.ts

failed Building development bundle - 42.797s
ERROR in ./src/design-system/theme.css.ts
Module build failed (from 
../../node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
ModuleBuildError: Module build failed (from ../../node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at /Users/phil/Code/newrade-core/node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js:311:23
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:548:11
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1118:17
    at Hook.eval [as callAsync] (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
 <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1114:33
    at finalCallback (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2249:11)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2540:11
    at Hook.eval [as callAsync] (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
 <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2533:38
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)
    at _next0 (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)
    at processResult (/Users/phil/Code/newrade-core/node_modules/webpack/lib/NormalModule.js:701:19)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/NormalModule.js:807:5
    at /Users/phil/Code/newrade-core/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/phil/Code/newrade-core/node_modules/loader-runner/lib/LoaderRunner.js:195:20
    at context.callback (/Users/phil/Code/newrade-core/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/phil/Code/newrade-core/node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js:311:14
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:548:11
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1118:17
    at Hook.eval [as callAsync] (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
 <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1114:33
    at finalCallback (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2249:11)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2540:11
    at Hook.eval [as callAsync] (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
 <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2533:38
 @ ./gatsby-wrap-element.tsx 10:0-39 11:0-59 71:26-36
 @ ./gatsby-browser.jsx 8:0-52 20:42-53
 @ ./.cache/api-runner-browser-plugins.js 115:10-42
 @ ./.cache/api-runner-browser.js 4:16-55
 @ ./.cache/app.js 10:0-65 27:87-31:1 35:20-29 48:0-14 112:19-28 146:6-15 27:0-31:2

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

What bothers me is I have 0 information in the stack trace to find out what is going on...

with `DEBUG=vanilla-extract:loader*`

I see no error either:

![image](https://user-images.githubusercontent.com/9644867/125140492-9f9b8e00-e0e0-11eb-87e1-36fff5e501cc.png)

Is there a way to get better error information ?

### Link to reproduction

I might have to create a repro here... unless you can tell me what to look for

Creating a repro is going to take me a good amount of time, it's a 20 packages monorepo so I'd have to create at least 1 ui lib, 1 gatsby site and 1 type repo where the shape of my design system lives

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 1.80 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.4.1 - ~/.nvm/versions/node/v16.4.1/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.1/bin/npm
  Browsers:
    Brave Browser: 91.1.25.68
    Chrome: 91.0.4472.114
    Safari: 14.1.1
```

PS. I'm migrating from treat

**Comment by phil-lgr** [comment]
I debugged the issue in gatsby and found out that `mini-css-extract-plugin` was crashing because an error in a .treat file

I separated my .treat.ts and .css.ts files in my ui lib and the error went away
