### ISSUE TITLE
mini-css-extract-plugin error on nextjs 

### ISSUE THREAD

**Issue by ryanpark** [seek-oss/vanilla-extract#287]
Hi, Thanks for great library 👍 
I am having following error after installed **mini-css-extract-plugin**.
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Cannot find module 'webpack/lib/util/identifier'
Require stack:
- /node_modules/mini-css-extract-plugin/dist/index.js
- /node_modules/mini-css-extract-plugin/dist/cjs.js
- /next.config.js
- /node_modules/next/dist/server/config.js
- /node_modules/next/dist/server/next.js
- /node_modules/next/dist/server/lib/start-server.js
- /node_modules/next/dist/cli/next-dev.js
- /node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (//node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (//node_modules/mini-css-extract-plugin/dist/index.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/mini-css-extract-plugin/dist/index.js',
    '/node_modules/mini-css-extract-plugin/dist/cjs.js',
    '/next.config.js',
    '/node_modules/next/dist/server/config.js',
    '/node_modules/next/dist/server/next.js',
    '/node_modules/next/dist/server/lib/start-server.js',
    '/node_modules/next/dist/cli/next-dev.js',
    '/node_modules/next/dist/bin/next'
  ]
}
```
next.config.js

```
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  plugins: [
    new VanillaExtractPlugin(),
    new MiniCssExtractPlugin()
  ],
  module: {
    rules: [
      {
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: require.resolve('css-loader'),
            options: {
              url: false // Required as image imports should be handled via JS/TS import statements
            }
          }
        ]
      }
    ]
  }
};
```

.babelrc

```
{
    "presets": ["next/babel"],
    "plugins": ["@vanilla-extract/babel-plugin"]
  }
```

**Comment by markdalgleish** [comment]
Can you please provide a working reproduction of the issue?

**Comment by ryanpark** [comment]
All good

**Comment by shyamlohar** [comment]
@ryanpark can you tell me what did you do to solve this error? I am facing same error.

**Comment by shyamlohar** [comment]
I am using nextJS and I tried setting up vanilla extract as per the steps mentioned for webpack. 

here is the error that I am getting 

```
{ Error: Cannot find module 'webpack/lib/util/identifier'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.mod._resolveFilename (/Users/shyamlohar/Documents/hobby-projects/ecommerce-template/node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/shyamlohar/Documents/hobby-projects/ecommerce-template/node_modules/mini-css-extract-plugin/dist/index.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) code: 'MODULE_NOT_FOUND' }
```
    
   I have installed the mini-css-extract-plugin as well as css loader as a dev dependency. 
   
   Dev server works fine if I add webpack as dev dependency but still CSS file is not getting extracted and styles are not  
   reflecting on page.

My `next.config.js` looks like 

```const withPlugins = require('next-compose-plugins');
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = withPlugins(
  [new VanillaExtractPlugin(), new MiniCssExtractPlugin()],
  {
    reactStrictMode: true,
    webpack: (config, options) => {
      config.module.rules.push({
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: require.resolve('css-loader'),
            options: {
              url: false // Required as image imports should be handled via JS/TS import statements
            }
          }
        ]
      });
      return config;
    }
  }
);
```
my `.babelrc` file looks like below 

```
{
  "presets": ["next/babel"],
  "plugins": ["@vanilla-extract/babel-plugin"]
}
```
I am attaching a repo link which can be used to reproduce it.  (vanilla-extract branch) 

https://github.com/shyamlohar/next-js-boilerplate/tree/vanilla-extract

If you need more information please let me know i will be glad to help with it. Thank you so much for creating this amazing lib <3
