### ISSUE TITLE
Issue building SvelteKit site

### ISSUE THREAD

**Issue by rodneylab** [seek-oss/vanilla-extract#359]
### Describe the bug

Unable to build SvelteKit site using @vanilla-extract/vite-plugin.  Site works fine in dev mode. However build, using a the static SvelteKit adapter fails.  Tried using the vite optimizeDeps option but same issue occurs whether I include this or not.  Build error message:

<details>
  <summary>Build error message</summary>
> Using @sveltejs/adapter-static
> Directory import '/XXX/sveltekit-vanilla-extract/node_modules/@vanilla-extract/css/fileScope' is not supported resolving ES modules imported from /XXX/sveltekit-vanilla-extract/.svelte-kit/output/server/app.js
Did you mean to import @vanilla-extract+css@1.5.1/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.js?
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/XXX/sveltekit-vanilla-extract/node_modules/@vanilla-extract/css/fileScope' is not supported resolving ES modules imported from /XXX/sveltekit-vanilla-extract/.svelte-kit/output/server/app.js
Did you mean to import @vanilla-extract+css@1.5.1/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.js?
    at finalizeResolution (internal/modules/esm/resolve.js:281:17)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36)
 ELIFECYCLE  Command failed with exit code 1.
</details>

### Link to reproduction

https://github.com/rodneylab/vanilla-extract-minimal

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.11 - ~/.npm-global/bin/yarn
    npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
  Browsers:
  npmPackages:
    @vanilla-extract/css: ^1.5.1 => 1.5.1 
    @vanilla-extract/vite-plugin: 2.0.0 => 2.0.0 
```

**Comment by rodneylab** [comment]
Thanks Ben, that's hit the spot! I tried the `noExternal` tweak but I was missing the `@vanilla-extract/css/fileScope` element.  Happy for you to close this, but appreciate you might want to keep it open to track ESM compatibility.

I'll drop a blog post next week on using vanilla extract with SvelteKit (all being well) and will give you a mention.

Thanks for your help.
