### ISSUE TITLE
Nuxtjs 3 + vanilla extract build error

### ISSUE THREAD

**Issue by rubenmoya** [seek-oss/vanilla-extract#413]
### Describe the bug

Nuxt 3 beta has been released and I was trying to use vanilla-extrat with it. I installed the vite plugin and added it to the `nuxt.config.ts` file. After running `yarn dev` I get this error:

```
some_folder/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.esm.js:1
import outdent from 'outdent';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async __instantiateModule__ (file://some_folder/.nuxt/dist/server/server.mjs:2319:3)
```

Let me know if there is any more information I can give you.

### Link to reproduction

https://codesandbox.io/s/nuxt3-vanilla-extract-cpfce

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 3.24 GB / 15.57 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 14.17.6 - /tmp/fnm_multishells/1605_1634115304080/bin/node
    Yarn: 1.22.11 - /tmp/fnm_multishells/1605_1634115304080/bin/yarn
    npm: 6.14.15 - /tmp/fnm_multishells/1605_1634115304080/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 93.0
  npmPackages:
    @vanilla-extract/css: ^1.6.2 => 1.6.2
    @vanilla-extract/vite-plugin: ^2.1.3 => 2.1.3
```

**Comment by leithonenglish** [comment]
I have a similar issue when I try to integrate `vanilla extract`. I get a slightly different error even when I try to add the plugin with what's above ☝🏼.
Error: `couldn't find parent package.json with a name field`. Anyone has any fix for this as yet?

**Comment by tkofh** [comment]
> I have a similar issue when I try to integrate `vanilla extract`. I get a slightly different error even when I try to add the plugin with what's above ☝🏼. Error: `couldn't find parent package.json with a name field`. Anyone has any fix for this as yet?

@leithonenglish This error can be resolved by adding `"name": "my-app"` (or whatever name you choose) to your project's `package.json`. Vanilla Extract looks for the package name to prepend to the virtual modules it creates.

**Comment by leithonenglish** [comment]
That works perfectly but now when I try to import any of the styles, for example,
`app.css.ts`
```ts
import { style } from "@vanilla-extract/css";

export const wrapperStyle = style({
  background: `red`,
});

```
`app.vue`
```vue
<script lang="ts" setup>
import { wrapperStyle } from "./app.css";
</script>
<template>
  <div :class="wrapperStyle">Hey there</div>
</template>
```

I get the following warning `(node:43589) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.` and the server never loads the page.
I tried getting info from here https://v3.nuxtjs.org/guide/going-further/esm/ but still not sure what I am missing

**Comment by leithonenglish** [comment]
No updates on this?

**Comment by ljani** [comment]
> I get the following warning (node:43589) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. and the server never loads the page.

I think I'm facing the same issue with SvelteKit. [Someone commented that Node does not like `.esm.js`](https://github.com/sveltejs/kit/issues/5535#issuecomment-1184922238) and it should be eg. `vanilla-extract-css.mjs`.

**Comment by ljani** [comment]
Renaming the file to end with `.mjs` seems to work for me. [Here's another one suggesting fixing the extension](https://github.com/sveltejs/kit/issues/7154#issuecomment-1269153189).

**Comment by ljani** [comment]
Okay, my error seems to be fixed by updating to Vite 4.0.3 released 5 hours ago, heh. I guess [it was this one](https://github.com/vitejs/vite/issues/11385).

Anyway, `.mjs` should be used over `.esm.js` and `css-what` should be upgraded to v6 so it is ESM, not CJS.

**Comment by graup** [comment]
I just tested this and don't seem to get any errors. If nobody has anything to add here, I'd close this issue.
