### ISSUE TITLE
Nuxt 3 + Vanilla Extract Vite `nuxt build` Error

### ISSUE THREAD

**Issue by tkofh** [seek-oss/vanilla-extract#446]
### Describe the bug

Running `yarn build` (`nuxt build` is the actual command) in a project that uses the Vanilla Extract Vite plugin produces this error:

```
▶ yarn build
yarn run v1.22.15
$ nuxt build
Nuxt CLI v3.0.0-27255771.f78ec93

 ERROR  [vite:css] /Users/timothymorris/Projects/vanilla-extract-ssr-error/styles.css.ts$$$nuxt3-vanilla-extract-ssr-error.vanilla.css:1:10: Unknown word
file: styles.css.ts$$$nuxt3-vanilla-extract-ssr-error.vanilla.css


 ERROR  /Users/timothymorris/Projects/vanilla-extract-ssr-error/styles.css.ts$$$nuxt3-vanilla-extract-ssr-error.vanilla.css:1:10: Unknown word

  at Input.error (node_modules/postcss/lib/input.js:123:16)
  at Parser.unknownWord (node_modules/postcss/lib/parser.js:518:22)
  at Parser.other (node_modules/postcss/lib/parser.js:149:12)
  at Parser.parse (node_modules/postcss/lib/parser.js:59:16)
  at parse (node_modules/postcss/lib/parse.js:11:12)
  at new LazyResult (node_modules/postcss/lib/lazy-result.js:133:16)
  at Processor.process (node_modules/postcss/lib/processor.js:36:12)
  at compileCSS (node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:20288:10)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async Object.transform (node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:19876:50)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Link to reproduction

[Repo](https://github.com/tkofh/nuxt3-vanilla-extract-ssr-error) (Reused from #445, though I don't believe these issues to be related)

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 49.77 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 89.0.1
    Safari: 15.1
  npmPackages:
    @vanilla-extract/css: ^1.6.3 => 1.6.3 
    @vanilla-extract/vite-plugin: ^3.0.0 => 3.0.0 
```

**Comment by tkofh** [comment]
I've updated the example repo with a static css file for comparison in behavior, and upgraded all the deps. Still seeing the above error when trying to build the project.

**Comment by Ttou** [comment]
same error

**Comment by tkofh** [comment]
After a bit more investigation, it appears that during `build`, this code is being fed into `postcss`:

```typescript
import { injectStyles } from '@vanilla-extract/css/injectStyles';                                                                                                                                                                                                                                                                                                15:33:58

const inject = (css) => injectStyles({
  fileScope: {"filePath":"styles/reset.css.ts","packageName":"my-app"},
  css
});

inject("/* my css here, omitted for brevity */");

import.meta.hot.on('vanilla-extract-style-update:styles/reset.css.ts$$$my-app', (css) => {
  inject(css);
});   
```

which appears to match the output of [`@vanilla-extract/vite-plugin/src/index.ts` lines 90-103](https://github.com/seek-oss/vanilla-extract/blob/master/packages/vite-plugin/src/index.ts#L90-L103). 

Ultimately its become clear that this is a Nuxt 3 issue not a vanilla-extract issue (as this works perfectly with vite out of the box), but does anybody have any ideas on what configuration might cause postcss to receive the above code (rather than what I assume is the output of running that code)?
