### ISSUE TITLE
Rollup plugin throws an error when in watch mode

### ISSUE THREAD

**Issue by roginfarrer** [seek-oss/vanilla-extract#691]
### Describe the bug
`@vanilla-extract/rollup-plugin` throws the following error when in watch mode:

```
[!] (plugin vanilla-extract) Error: Plugin error - Unable to get file name for unknown file "3f979318".
Error: Plugin error - Unable to get file name for unknown file "3f979318".
    at error (/Users/rfarrer/projects/vanilla-extract-rollup-example/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Object.FileEmitter.getFileName (/Users/rfarrer/projects/vanilla-extract-rollup-example/node_modules/rollup/dist/shared/rollup.js:15589:24)
    at /Users/rfarrer/projects/vanilla-extract-rollup-example/node_modules/@vanilla-extract/rollup-plugin/dist/vanilla-extract-rollup-plugin.cjs.dev.js:82:32
    at Array.reduce (<anonymous>)
    at Object.renderChunk (/Users/rfarrer/projects/vanilla-extract-rollup-example/node_modules/@vanilla-extract/rollup-plugin/dist/vanilla-extract-rollup-plugin.cjs.dev.js:80:31)
    at /Users/rfarrer/projects/vanilla-extract-rollup-example/node_modules/rollup/dist/shared/rollup.js:22834:37
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Link to reproduction
1. Clone this repo https://github.com/graup/vanilla-extract-rollup-example
2. cd into packages/ui
3. Run `yarn rollup -c --watch`
4. Make a change to a `.css.ts` file and save

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 398.45 MB / 16.00 GB
    Shell: 3.4.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.0.0 - ~/Library/Caches/fnm_multishells/26791_1652796954290/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - ~/Library/Caches/fnm_multishells/26791_1652796954290/bin/npm
  Browsers:
    Brave Browser: 101.1.38.115
    Chrome: 101.0.4951.64
    Firefox: 98.0.2
    Firefox Developer Edition: 99.0
    Safari: 15.4
```

**Comment by graup** [comment]
Thanks for the report, I'll look into that. Hadn't actually tested watch mode much 😅

**Comment by segunadebayo** [comment]
+1 Getting this error has well. Really looking forward to the fix!

Thanks for this amazing library 💖
